# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
#for dimension use .ndim
print(A.ndim)

#for shape use .shape
print(A.shape)

#for size use .size 
print(A.size)

#for data type use .dtype
print(A.dtype)


2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [9]:
B = np.arange(1, 10).reshape(3, 3) #to reshape B use .reshape to shape into a (3,3) to match C 
C = np.ones((3, 3))*2

print(B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [15]:
subtraction = B - C 
print(subtraction) 

elementwise_multiplication = B * C
print(elementwise_multiplication)

matrix_multiplication = B @ C  #we can also use np.dot(B, C) for matrix multiplication 
print(matrix_multiplication)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [23]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
exp_B = np.exp(B) #exponentiate = alltså talet e upphöjt till talet i matrisen  
min_B_whole = np.min(B)
min_B_rows = np.min(B, axis=1) #axis 1 points to rows
min_B_columns = np.min(B, axis=0) #axis 0 points to columns
min_index = np.argmin(B)
min_index_rows = np.argmin(B, axis=1)
sum_all = B.sum()
mean_per_column = np.mean(B, axis=0)
median_per_column = np.median(B, axis=0)

print(exp_B)
print(min_B_whole)
print(min_B_rows)
print(min_B_columns)
print(min_index)
print(min_index_rows)
print(sum_all)
print(mean_per_column)
print(median_per_column)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [34]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [36]:
#When we provide fewer indices than axes when slicing, as in the showed example,
#NumPy assumes we want the whole of the second row and will return all columns in the specified row.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [37]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
#with respect to first axis 
for i in A: 
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [41]:
#iterate over each element 
for i in np.nditer(A): 
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [45]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Answer:
Instead of a 2D array with rows and columns, we here have a 3D array and therefor also three axes. The first axis (axis 0) represents more complex data structure, ie. blocks or layers of data, the second (axis 1) represents rows within those blocks, and the third axis (axis 2) represents the columns within each row. 
In the example above we have 2 blocks, with each 3 rows, and the -1 in reshape tells Python to figure out the size of this dimension, columns, over the amount of 30 digits that we have. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [46]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [47]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [49]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [34]:
import numpy as np 

def add_mult_matrices(m1, m2, operation):
    #validate that the input is type numpy.ndarray
    if not isinstance(m1, np.ndarray) or not (m2, np.ndarray):
        raise ValueError("Both matrices must be of type numpy ndarray.")
    
    #Also validade operation argument is add or multiply
    if operation not in ["add", "multiply"]:
        raise ValueError("Choose either add och multiply for the matrices")
    
    #Matrix addition, validate same size 
    if operation == "add":
        if m1.shape != m2.shape:
            raise ValueError("Matrices have to have the same size for addition")
        return m1 + m2 

    #Matrix multiplication, validate sizes conform 
    elif operation == "multiply":
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal to the number of rows in the second matrix")
        return m1 @ m2 


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [13]:
# 10.1.1 
x = np.array([[4,3]])

A = x.shape
B = 5*x
C = 3*x
D = B + C
E = 8*x
F = (4*x) - x
G = x.T
H = x + G #Not defined, but NumPy makes their dimension match by Broadcasting. 
I = np.linalg.norm(x)

print(A)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(G.shape)
print(H)
print(I)


(1, 2)
[[20 15]]
[[12  9]]
[[32 24]]
[[32 24]]
[[12  9]]
[[4]
 [3]]
(2, 1)
[[8 7]
 [7 6]]
5.0


In [26]:
#10.1.2 
v = np.array([[3], [7], [0], [11]])

B = 2*v 
C = (5*v) + (2*v)
D = (4*v) - (2*v)
E = v.T 
F = np.linalg.norm(v)

print("v has the dimesion:",v.shape) #a
print(B) #b 
print(C) #c
print(D) #d
print(E.shape) #e
print(F) #f  

v has the dimesion: (4, 1)
[[ 6]
 [14]
 [ 0]
 [22]]
[[21]
 [49]
 [ 0]
 [77]]
[[ 6]
 [14]
 [ 0]
 [22]]
(1, 4)
13.379088160259652


In [29]:
#10.1.3
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

A = np.linalg.norm(v1)
B = np.linalg.norm(v1-v2)

print(A)
print(B)

7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [36]:
# 10.2.1
A = np.array([2, 1, -1, 1, -1, 1]).reshape((2, 3))
B = np.array([4, -2, 1, 2, -4, -2]).reshape((2, 3))
C = np.array([1, 2, 2, 1]).reshape((2, 2))
D = np.array([3, 4, 4, 3]).reshape((2, 2))
E = np.array([[1],[2]])
I = np.array([1, 0, 0, 1]).reshape((2,2))

print(2*A) #a 
print(B - (2*A)) #b
#c undefined
print(add_mult_matrices(2*D, -3*C, "add")) #d
print(add_mult_matrices(D.T, 2*D, "add")) #e
print(add_mult_matrices(2*C.T, -2*D.T, "add")) #f
#g undefined
#h undefined
print(add_mult_matrices(C, D, "multiply")) #i
print(add_mult_matrices(C, B, "multiply")) #j
print(add_mult_matrices(C, I, "multiply")) #k
print(add_mult_matrices(A, B.T, "multiply")) #l


[[ 4  2 -2]
 [ 2 -2  2]]
[[ 0 -4  3]
 [ 0 -2 -4]]
[[3 2]
 [2 3]]
[[ 9 12]
 [12  9]]
[[-4 -4]
 [-4 -4]]
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]
[[1 2]
 [2 1]]
[[5 2]
 [7 4]]


In [38]:
# 10.2.2
A = np.array([[2, 3, 4], [5, 4, 1]])

print(add_mult_matrices(A, A.T, "multiply"))

[[29 26]
 [26 42]]


In [41]:
# 10.2.3
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1,3]])
C = np.array([[4, 3], [0, 2]])

print(add_mult_matrices(A, B, "multiply"))
print(add_mult_matrices(A, C, "multiply")) 

[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [51]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [52]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [53]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
